name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.0'
          channel: 'stable'
      - name: Getting Packages
        run: flutter pub get
      - name: Build APK
        run: flutter build apk
      - name: Upload Release Apk
        uses: actions/upload-artifact@v2.3.1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
